server:
  port: 9092
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/iesApp
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  mail:
    host: smtp.gmail.com
    password: jcehpqiiusebmsuh
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    username: akumar69141@gmail.com